version: '3.1'

services:
  mountaincam-7s:
    # Build from source
    build: .
    # Or use the pre-build
    # image: wenoptics/discord-image-bot:latest
    command:
      - --discord_webhook_url
      - https://discord.com/api/webhooks/<your-secret>/<your-secret-token>
      - --image_url
      - https://live8p.brownrice.com/cam-images/sevensprings.jpg
      # Every 45 minutes
      - --cron
      - '*/45 * * * *'

  mountaincam-boycepark:
    # Build from source
    build: .
    # Or use the pre-build
    # image: wenoptics/discord-image-bot:latest
    command:
      - --discord_webhook_url
      - https://discord.com/api/webhooks/<your-secret>/<your-secret-token>
      - --image_url
      - https://b7.hdrelay.com/camera/14ced094-b906-401c-bd83-06dc36f4c2db/snapshot
      # Every 45 minutes
      - --cron
      - '*/45 * * * *'
